#!/bin/bash

# ============================================================================
# SKILL SYNC - Synchronizes skills and agents across the project
# Based on Gentleman Programming's architecture for AI agents
# ============================================================================

set -e

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILLS_DIR="$PROJECT_ROOT/skills"
AGENTS_DIR="$PROJECT_ROOT/.claude/agents"
OPENCODE_DIR="$HOME/.config/opencode"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}╔════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║        SKILL SYNC v1.0                 ║${NC}"
echo -e "${BLUE}║   LogiAccounting Pro Agent Skills      ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════╝${NC}"
echo ""

# ============================================================================
# VALIDATE SKILLS
# ============================================================================
echo -e "${YELLOW}📋 Validating Skills...${NC}"

validate_skill() {
    local skill_file="$1"
    local skill_name=$(basename $(dirname "$skill_file"))
    
    # Check YAML frontmatter
    if ! head -1 "$skill_file" | grep -q "^---$"; then
        echo -e "${RED}  ✗ $skill_name: Missing YAML frontmatter${NC}"
        return 1
    fi
    
    # Check required fields
    if ! grep -q "^name:" "$skill_file"; then
        echo -e "${RED}  ✗ $skill_name: Missing 'name' field${NC}"
        return 1
    fi
    
    if ! grep -q "^description:" "$skill_file"; then
        echo -e "${RED}  ✗ $skill_name: Missing 'description' field${NC}"
        return 1
    fi
    
    # Check description length (min 20 chars)
    local desc=$(grep "^description:" "$skill_file" | cut -d':' -f2- | xargs)
    if [ ${#desc} -lt 20 ]; then
        echo -e "${YELLOW}  ⚠ $skill_name: Description too short (min 20 chars)${NC}"
    fi
    
    echo -e "${GREEN}  ✓ $skill_name${NC}"
    return 0
}

skill_count=0
valid_count=0

for skill_dir in "$SKILLS_DIR"/*/; do
    if [ -f "$skill_dir/SKILL.md" ]; then
        ((skill_count++))
        if validate_skill "$skill_dir/SKILL.md"; then
            ((valid_count++))
        fi
    fi
done

echo -e "${BLUE}  Skills validated: $valid_count/$skill_count${NC}"
echo ""

# ============================================================================
# VALIDATE AGENTS
# ============================================================================
echo -e "${YELLOW}🤖 Validating Agents...${NC}"

validate_agent() {
    local agent_file="$1"
    local agent_name=$(basename "$agent_file" .md)
    
    # Check YAML frontmatter
    if ! head -1 "$agent_file" | grep -q "^---$"; then
        echo -e "${RED}  ✗ $agent_name: Missing YAML frontmatter${NC}"
        return 1
    fi
    
    # Check required fields
    if ! grep -q "^name:" "$agent_file"; then
        echo -e "${RED}  ✗ $agent_name: Missing 'name' field${NC}"
        return 1
    fi
    
    if ! grep -q "^description:" "$agent_file"; then
        echo -e "${RED}  ✗ $agent_name: Missing 'description' field${NC}"
        return 1
    fi
    
    echo -e "${GREEN}  ✓ $agent_name${NC}"
    return 0
}

agent_count=0
valid_agents=0

if [ -d "$AGENTS_DIR" ]; then
    for agent_file in "$AGENTS_DIR"/*.md; do
        if [ -f "$agent_file" ]; then
            ((agent_count++))
            if validate_agent "$agent_file"; then
                ((valid_agents++))
            fi
        fi
    done
fi

echo -e "${BLUE}  Agents validated: $valid_agents/$agent_count${NC}"
echo ""

# ============================================================================
# GENERATE SKILL INDEX
# ============================================================================
echo -e "${YELLOW}📚 Generating Skill Index...${NC}"

INDEX_FILE="$SKILLS_DIR/INDEX.md"

cat > "$INDEX_FILE" << 'HEADER'
# LogiAccounting Pro - Agent Skills Index

This file is auto-generated by `skill-sync.sh`. Do not edit manually.

## Available Skills

| Skill | Description | Category |
|-------|-------------|----------|
HEADER

for skill_dir in "$SKILLS_DIR"/*/; do
    if [ -f "$skill_dir/SKILL.md" ]; then
        skill_name=$(basename "$skill_dir")
        description=$(grep "^description:" "$skill_dir/SKILL.md" | cut -d':' -f2- | xargs | cut -c1-60)
        category=$(grep "category:" "$skill_dir/SKILL.md" | cut -d':' -f2- | xargs || echo "general")
        echo "| \`\$$skill_name\` | $description... | $category |" >> "$INDEX_FILE"
    fi
done

cat >> "$INDEX_FILE" << 'FOOTER'

## Available Agents

| Agent | Description | Model |
|-------|-------------|-------|
FOOTER

if [ -d "$AGENTS_DIR" ]; then
    for agent_file in "$AGENTS_DIR"/*.md; do
        if [ -f "$agent_file" ]; then
            agent_name=$(basename "$agent_file" .md)
            description=$(grep "^description:" "$agent_file" | cut -d':' -f2- | xargs | cut -c1-60)
            model=$(grep "^model:" "$agent_file" | cut -d':' -f2- | xargs || echo "default")
            echo "| \`@$agent_name\` | $description... | $model |" >> "$INDEX_FILE"
        fi
    done
fi

cat >> "$INDEX_FILE" << 'USAGE'

## Usage

### Invoking Skills
```
$backend    # Load backend development patterns
$frontend   # Load React component patterns
$testing    # Load test writing patterns
```

### Invoking Agents
```
@code-reviewer  # Get code reviewed
@api-designer   # Design new API endpoints
@test-writer    # Write tests for code
@debugger       # Debug issues
```

### Skill + Agent Combination
```
@test-writer with $testing skill, write tests for the auth module
```

---
*Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")*
USAGE

echo -e "${GREEN}  ✓ Index generated: $INDEX_FILE${NC}"
echo ""

# ============================================================================
# SYNC TO OPENCODE (if installed)
# ============================================================================
if command -v opencode &> /dev/null && [ -d "$OPENCODE_DIR" ]; then
    echo -e "${YELLOW}🔄 Syncing to OpenCode...${NC}"
    
    # Create OpenCode skill directory if needed
    mkdir -p "$OPENCODE_DIR/skill"
    
    # Copy skills to OpenCode
    for skill_dir in "$SKILLS_DIR"/*/; do
        if [ -f "$skill_dir/SKILL.md" ]; then
            skill_name=$(basename "$skill_dir")
            cp -r "$skill_dir" "$OPENCODE_DIR/skill/"
            echo -e "${GREEN}  ✓ Synced: $skill_name${NC}"
        fi
    done
    
    echo ""
fi

# ============================================================================
# SUMMARY
# ============================================================================
echo -e "${BLUE}╔════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║              SYNC COMPLETE             ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════╝${NC}"
echo ""
echo -e "  Skills:  ${GREEN}$valid_count${NC} valid"
echo -e "  Agents:  ${GREEN}$valid_agents${NC} valid"
echo -e "  Index:   ${GREEN}$INDEX_FILE${NC}"
echo ""
echo -e "${YELLOW}💡 Tip: Run this script after modifying skills or agents${NC}"
